language: cpp

dist: trusty
sudo: required
services: docker

matrix:
  include:
    - os: linux

    - os: linux
      env: USE_HDFS="ON"

    - os: linux
      env: USE_S3="ON"

    - os: osx

install:
    # Install clangformat (v5.0)
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo scripts/install-clangformat.sh;
      else
        scripts/install-clangformat.sh;
      fi

    # Set up arguments for install-deps.sh
    - deps_args=""
      if [[ "$USE_HDFS" == "ON" ]]; then
        deps_args="${deps_args} --enable-hdfs"
      fi
      if [[ "$USE_S3" == "ON" ]]; then
        deps_args="${deps_args} --enable-s3"
      fi

    # Install library dependencies
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo scripts/install-deps.sh $deps_args;
      else
        scripts/install-deps.sh $deps_args;
      fi

    - mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build

      # Build TileDB
    - if [[ "$USE_HDFS" == "ON" ]]; then
        ../bootstrap --enable-coverage --enable-verbose --enable-hdfs;
      elif [[ "$USE_S3" == "ON" ]]; then
        ../bootstrap --enable-coverage --enable-verbose --enable-s3;
      else
        ../bootstrap --enable-coverage --enable-verbose;
      fi

    - make -j4
    - make examples -j4
    
script:
    - make check-format
    - make check
